# This is the Github Action version of the original travis.yml. We thought it would be a nice task to migrate the CI workflow to GitHub actions.

name: Build CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    name: Build CI 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: |
        pip install -r test_requirements.txt
        
    #Running checks before installation
    #     black is to check if files would need some reformatting
    #     stopping the build if there are Python sytax errors or undefined names
    #     exit-zero treats all errors as warnings, The github editor is 127 chars wide
    - name: Checks before install
      run: |
        black --check . || true
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 

    # Runs a set of commands using the runners shell
    - name: Check Package install
      run: |
        pip install -e .
        python -m tox
        pip uninstall -y algorithms
